version: '3.7'

services:
  mariadb:
    container_name: mariadb
    build:
      context: srcs/mariadb/
      args:
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=rimney
        - MYSQL_PASSWORD=1234
        - MYSQL_ROOT_PASSWORD=1234
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ${PWD}/srcs/wordpress/
    environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=rimney
        - MYSQL_PASSWORD=1234
        - MYSQL_ROOT_PASSWORD=1234
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always

  nginx:
    networks:
      - inception
    container_name: nginx
    build: srcs/nginx/
    depends_on:
      - wordpress
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/rimney/mysql
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/rimney/wordpress
      o: bind
