version: '3.7'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs/mariadb/
      # args:
      #   MYSQL_DATABASE: wordpress
      #   MYSQL_USER: rimney
      #   MYSQL_PASSWORD: 1234
      #   MYSQL_ROOT_PASSWORD: 1234
    env_file:
      - .env
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress/
    # environment:
    #   - MYSQL_DATABASE=wordpress
    #   - MYSQL_USER=rimney
    #   - MYSQL_PASSWORD=1234
    #   - MYSQL_ROOT_PASSWORD=1234
    #   - MYSQL_HOSTNAME=mariadb
    #   - DOMAIN_NAME=localhost
    #   - WP_USER=rimney
    #   - WP_ADMIN_USER=rimney42
    #   - WP_ADMIN_PW=1234
    #   - WP_ADMIN_EMAIL=rimney13@gmail.com
    #   - WP_EMAIL=rimney13@gmail.com
    #   - WP_PW=1234
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always

  nginx:
    networks:
      - inception
    container_name: nginx
    build: ./srcs/nginx/
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db_data:
  wp_data:
